name: marcusjroberts
favicon: null
layout_spectrum: 0.7569
typography_spectrum: 0.20349
title: 'Marc Roberts: Creative Technologist, etc.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a3221'
    - '#52452f'
    - '#746347'
    - '#897351'
  brandStrength: 0.960352127905935
  lightness: 0
  saturation: 0.13507100963033736
  rhythmicContrast: 0.29146226681768894
purpose: []
